import { Product, Category, Supplier, PurchaseOrder, SalesOrder, StockTransaction } from './types';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Electronics', description: 'Electronic devices and components', createdAt: new Date() },
  { id: '2', name: 'Clothing', description: 'Apparel and fashion items', createdAt: new Date() },
  { id: '3', name: 'Home & Garden', description: 'Home improvement and gardening supplies', createdAt: new Date() },
  { id: '4', name: 'Books', description: 'Books and educational materials', createdAt: new Date() },
  { id: '5', name: 'Sports', description: 'Sports equipment and accessories', createdAt: new Date() },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: '1',
    name: 'Tech Solutions Ltd',
    email: 'orders@techsolutions.com',
    phone: '+1-555-0123',
    address: '123 Tech Street, Silicon Valley, CA 94025',
    contactPerson: 'John Smith',
    paymentTerms: 'Net 30',
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Fashion Direct',
    email: 'procurement@fashiondirect.com',
    phone: '+1-555-0456',
    address: '456 Fashion Ave, New York, NY 10001',
    contactPerson: 'Sarah Johnson',
    paymentTerms: 'Net 15',
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Home Essentials Co',
    email: 'sales@homeessentials.com',
    phone: '+1-555-0789',
    address: '789 Home Lane, Chicago, IL 60601',
    contactPerson: 'Mike Davis',
    paymentTerms: 'Net 30',
    createdAt: new Date(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'MacBook Pro 14"',
    sku: 'MBP-14-001',
    category: 'Electronics',
    description: 'Apple MacBook Pro 14" with M3 chip, 16GB RAM, 512GB SSD',
    unitPrice: 2199.99,
    costPrice: 1800.00,
    currentStock: 25,
    minStock: 10,
    maxStock: 50,
    unit: 'pcs',
    supplier: 'Tech Solutions Ltd',
    location: 'Warehouse A-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'iPhone 15 Pro',
    sku: 'IPH-15P-001',
    category: 'Electronics',
    description: 'Apple iPhone 15 Pro, 128GB, Natural Titanium',
    unitPrice: 999.99,
    costPrice: 800.00,
    currentStock: 15,
    minStock: 20,
    maxStock: 100,
    unit: 'pcs',
    supplier: 'Tech Solutions Ltd',
    location: 'Warehouse A-2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Designer Jeans',
    sku: 'DJ-001',
    category: 'Clothing',
    description: 'Premium designer jeans, various sizes',
    unitPrice: 89.99,
    costPrice: 45.00,
    currentStock: 150,
    minStock: 50,
    maxStock: 300,
    unit: 'pcs',
    supplier: 'Fashion Direct',
    location: 'Warehouse B-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Garden Tool Set',
    sku: 'GTS-001',
    category: 'Home & Garden',
    description: 'Complete garden tool set with spade, rake, and trowel',
    unitPrice: 49.99,
    costPrice: 25.00,
    currentStock: 75,
    minStock: 30,
    maxStock: 150,
    unit: 'set',
    supplier: 'Home Essentials Co',
    location: 'Warehouse C-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Programming Book',
    sku: 'PB-001',
    category: 'Books',
    description: 'Advanced JavaScript Programming Guide',
    unitPrice: 39.99,
    costPrice: 20.00,
    currentStock: 8,
    minStock: 15,
    maxStock: 100,
    unit: 'pcs',
    supplier: 'Tech Solutions Ltd',
    location: 'Warehouse D-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const MOCK_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: '1',
    orderNumber: 'PO-2024-001',
    supplierId: '1',
    supplierName: 'Tech Solutions Ltd',
    items: [
      {
        id: '1',
        productId: '1',
        productName: 'MacBook Pro 14"',
        quantity: 10,
        unitPrice: 1800.00,
        totalPrice: 18000.00,
        receivedQuantity: 10,
      },
      {
        id: '2',
        productId: '2',
        productName: 'iPhone 15 Pro',
        quantity: 20,
        unitPrice: 800.00,
        totalPrice: 16000.00,
        receivedQuantity: 20,
      },
    ],
    totalAmount: 34000.00,
    status: 'received',
    orderDate: new Date('2024-01-15'),
    expectedDate: new Date('2024-01-25'),
    receivedDate: new Date('2024-01-24'),
    createdBy: 'Manager User',
  },
  {
    id: '2',
    orderNumber: 'PO-2024-002',
    supplierId: '2',
    supplierName: 'Fashion Direct',
    items: [
      {
        id: '3',
        productId: '3',
        productName: 'Designer Jeans',
        quantity: 100,
        unitPrice: 45.00,
        totalPrice: 4500.00,
        receivedQuantity: 0,
      },
    ],
    totalAmount: 4500.00,
    status: 'pending',
    orderDate: new Date('2024-01-20'),
    expectedDate: new Date('2024-01-30'),
    createdBy: 'Manager User',
  },
];

export const MOCK_SALES_ORDERS: SalesOrder[] = [
  {
    id: '1',
    orderNumber: 'SO-2024-001',
    customerName: 'John Doe',
    customerEmail: 'john@example.com',
    items: [
      {
        id: '1',
        productId: '1',
        productName: 'MacBook Pro 14"',
        quantity: 2,
        unitPrice: 2199.99,
        totalPrice: 4399.98,
      },
    ],
    totalAmount: 4399.98,
    status: 'delivered',
    orderDate: new Date('2024-01-18'),
    deliveryDate: new Date('2024-01-22'),
    createdBy: 'Employee User',
  },
  {
    id: '2',
    orderNumber: 'SO-2024-002',
    customerName: 'Jane Smith',
    customerEmail: 'jane@example.com',
    items: [
      {
        id: '2',
        productId: '2',
        productName: 'iPhone 15 Pro',
        quantity: 1,
        unitPrice: 999.99,
        totalPrice: 999.99,
      },
      {
        id: '3',
        productId: '3',
        productName: 'Designer Jeans',
        quantity: 3,
        unitPrice: 89.99,
        totalPrice: 269.97,
      },
    ],
    totalAmount: 1269.96,
    status: 'confirmed',
    orderDate: new Date('2024-01-22'),
    createdBy: 'Employee User',
  },
];

export const MOCK_STOCK_TRANSACTIONS: StockTransaction[] = [
  {
    id: '1',
    productId: '1',
    productName: 'MacBook Pro 14"',
    type: 'in',
    quantity: 10,
    unitPrice: 1800.00,
    totalValue: 18000.00,
    reference: 'PO-2024-001',
    reason: 'Purchase order received',
    date: new Date('2024-01-24'),
    createdBy: 'Manager User',
  },
  {
    id: '2',
    productId: '1',
    productName: 'MacBook Pro 14"',
    type: 'out',
    quantity: 2,
    unitPrice: 2199.99,
    totalValue: 4399.98,
    reference: 'SO-2024-001',
    reason: 'Sales order fulfilled',
    date: new Date('2024-01-22'),
    createdBy: 'Employee User',
  },
  {
    id: '3',
    productId: '2',
    productName: 'iPhone 15 Pro',
    type: 'in',
    quantity: 20,
    unitPrice: 800.00,
    totalValue: 16000.00,
    reference: 'PO-2024-001',
    reason: 'Purchase order received',
    date: new Date('2024-01-24'),
    createdBy: 'Manager User',
  },
  {
    id: '4',
    productId: '5',
    productName: 'Programming Book',
    type: 'adjustment',
    quantity: -2,
    unitPrice: 20.00,
    totalValue: -40.00,
    reference: 'ADJ-001',
    reason: 'Damaged goods removed',
    date: new Date('2024-01-23'),
    createdBy: 'Manager User',
  },
];